/// Generated by AssetsRefGenerator on 2022/04/09
class Res {
  static const String burger = "assets/images/burger.jpg";
  static const String burrito = "assets/images/burrito.jpg";
  static const String pancakes = "assets/images/pancakes.jpg";
  static const String pasta = "assets/images/pasta.jpg";
  static const String pizza = "assets/images/pizza.jpg";
  static const String ramen = "assets/images/ramen.jpg";
  static const String restaurant0 = "assets/images/restaurant0.jpg";
  static const String restaurant1 = "assets/images/restaurant1.jpg";
  static const String restaurant2 = "assets/images/restaurant2.jpg";
  static const String restaurant3 = "assets/images/restaurant3.jpg";
  static const String restaurant4 = "assets/images/restaurant4.jpg";
  static const String salmon = "assets/images/salmon.jpg";
  static const String steak = "assets/images/steak.jpg";
}
